{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "5cf42859",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error occurred for link: http://masterplan.utep.edu/, Error: HTTPConnectionPool(host='masterplan.utep.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015CBE97A560>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error occurred for link: http://studentlife.utep.edu/, Error: HTTPConnectionPool(host='studentlife.utep.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015CBE4D8B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link checking completed.\n"
     ]
    }
   ],
   "source": [
    "import threading\n",
    "import requests\n",
    "import time\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def check_link(link):\n",
    "    try:\n",
    "        headers = {\n",
    "            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'\n",
    "        }\n",
    "        response = requests.get(link, headers=headers)\n",
    "        print(response.status_code)\n",
    "        \n",
    "        # Handle 429 status code\n",
    "        if response.status_code == 429:\n",
    "            print(f\"Rate limit exceeded for link: {link}\")\n",
    "            retry_after = int(response.headers.get('Retry-After', 10))\n",
    "            print(f\"Retrying after {retry_after} seconds...\")\n",
    "            time.sleep(retry_after)\n",
    "            response = requests.get(link, headers=headers)\n",
    "\n",
    "        # Check for CAPTCHA challenge\n",
    "        if \"recaptcha\" in link.lower() and \"demo\" in link.lower():\n",
    "            print(f\"CAPTCHA challenge encountered for link: {link}\")\n",
    "        elif response.status_code == 403:  # Example of a blocked status code\n",
    "            print(f\"Access blocked for link: {link}\")\n",
    "        elif response.status_code != 200:\n",
    "            print(f\"Broken link found: {link}\")\n",
    "        else:\n",
    "            print(f\"Link is okay: {link}\")\n",
    "    except requests.exceptions.SSLError as ssl_error:\n",
    "        # Attempt the request again with verify=False in case of SSL verification error\n",
    "        print(f\"SSL verification error occurred for link: {link}, Error: {ssl_error}\")\n",
    "        try:\n",
    "            response = requests.get(link, headers=headers, verify=False)\n",
    "            if response.status_code != 200:\n",
    "                print(f\"Broken link found (after retry): {link}\")\n",
    "            else:\n",
    "                print(f\"Link is okay (after retry): {link}\")\n",
    "        except requests.exceptions.RequestException as e:\n",
    "            print(f\"Error occurred for link (retry): {link}, Error: {e}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print(f\"Error occurred for link: {link}, Error: {e}\")\n",
    "\n",
    "\n",
    "        \n",
    "        \n",
    "\n",
    "\n",
    "# List of links to check\n",
    "links = [\n",
    "    #\"https://utepminers.com/\",  # Regular page\n",
    "    #\"http://givingto.utep.edu/page.aspx?pid=1425\",    # Regular page\n",
    "    #\"https://givingto.utep.edu/ways-of-giving\",    # Regular page\n",
    "    #\"https://www.utep.edu/giving/\",  # Regular page\n",
    "    #\"http://alumni.utep.edu/\",\n",
    "    \"http://masterplan.utep.edu/\",\n",
    "    \"http://studentlife.utep.edu/\",\n",
    "]\n",
    "\n",
    "\n",
    "# Create and start threads for each link\n",
    "threads = []\n",
    "for link in links:\n",
    "    thread = threading.Thread(target=check_link, args=(link,))\n",
    "    threads.append(thread)\n",
    "    thread.start()\n",
    "    time.sleep(1)  # Introduce a delay between requests\n",
    "\n",
    "# Wait for all threads to finish\n",
    "for thread in threads:\n",
    "    thread.join()\n",
    "\n",
    "print(\"Link checking completed.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b18357d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02098bd3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "c5960422",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "here\n",
      "Error occurred for link: http://masterplan.utep.edu/, Error: HTTPConnectionPool(host='masterplan.utep.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015CBE4DAB00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "here\n",
      "Error occurred for link: http://studentlife.utep.edu/, Error: HTTPConnectionPool(host='studentlife.utep.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015CBE4DA710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link checking completed.\n"
     ]
    }
   ],
   "source": [
    "import threading\n",
    "import requests\n",
    "import time\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def check_link(link):\n",
    "    try:\n",
    "        response = requests.get(link)\n",
    "        \n",
    "        print(response.status_code)\n",
    "        if response.status_code != 200:\n",
    "            print(f\"Broken link found: {link}\")\n",
    "        elif response.status_code ==200:\n",
    "            print(f\"Link is okay: {link}\")\n",
    "        else:\n",
    "            print(\"God knows...\")\n",
    "    except requests.exceptions.SSLError as ssl_error:\n",
    "        # Attempt the request again with verify=False in case of SSL verification error\n",
    "        print(f\"SSL verification error occurred for link: {link}, Error: {ssl_error}\")\n",
    "        try:\n",
    "            response = requests.get(link, headers=headers, verify=False)\n",
    "            print()\n",
    "            if response.status_code != 200:\n",
    "                print(f\"Broken link found (after retry): {link}\")\n",
    "            else:\n",
    "                print(f\"Link is okay (after retry): {link}\")\n",
    "        except requests.exceptions.RequestException as e:\n",
    "            print('here too')\n",
    "            print(f\"Error occurred for link (retry): {link}, Error: {e}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print('here')\n",
    "        print(f\"Error occurred for link: {link}, Error: {e}\")\n",
    "\n",
    "\n",
    "        \n",
    "        \n",
    "\n",
    "\n",
    "# List of links to check\n",
    "links = [\n",
    "    #\"https://utepminers.com/\",  # Regular page\n",
    "    #\"http://givingto.utep.edu/page.aspx?pid=1425\",    # Regular page\n",
    "    #\"https://givingto.utep.edu/ways-of-giving\",    # Regular page\n",
    "    #\"https://www.utep.edu/giving/\",  # Regular page\n",
    "    #\"http://alumni.utep.edu/\",\n",
    "    \"http://masterplan.utep.edu/\",\n",
    "    \"http://studentlife.utep.edu/\",\n",
    "]\n",
    "\n",
    "\n",
    "# Create and start threads for each link\n",
    "threads = []\n",
    "for link in links:\n",
    "    thread = threading.Thread(target=check_link, args=(link,))\n",
    "    threads.append(thread)\n",
    "    thread.start()\n",
    "    time.sleep(1)  # Introduce a delay between requests\n",
    "\n",
    "# Wait for all threads to finish\n",
    "for thread in threads:\n",
    "    thread.join()\n",
    "\n",
    "print(\"Link checking completed.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2442e847",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f53ca60e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5f4fbb45",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "42032918",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69d92e4d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "444b5eff",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ec198be8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "762cada6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error occurred for link: https://sao.fraud.texas.gov/, Error: HTTPSConnectionPool(host='sao.fraud.texas.gov', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com/recaptcha/api2/demo\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Broken link found: https://scholar.google.co.jp/citations?user=AQo7YOEAAAAJ&hl=en\n",
      "Link checking completed.\n"
     ]
    }
   ],
   "source": [
    "import threading\n",
    "import requests\n",
    "\n",
    "# Function to check a single link\n",
    "def check_link(link):\n",
    "    try:\n",
    "        response = requests.get(link)\n",
    "        if response.status_code != 200:\n",
    "            print(f\"Broken link found: {link}\")\n",
    "        else:\n",
    "            print(f\"Link is okay: {link}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print(f\"Error occurred for link: {link}, Error: {e}\")\n",
    "\n",
    "# List of links to check\n",
    "links = [\n",
    "    \"https://www.example.com\",\n",
    "    \"https://www.google.com\",\n",
    "    \"https://www.openai.com\",\n",
    "    \"https://scholar.google.co.jp/citations?user=AQo7YOEAAAAJ&hl=en\",\n",
    "    'https://sao.fraud.texas.gov/',\n",
    "    \"https://www.google.com/recaptcha/api2/demo\", \n",
    "]\n",
    "\n",
    "# Create and start threads for each link\n",
    "threads = []\n",
    "for link in links:\n",
    "    thread = threading.Thread(target=check_link, args=(link,))\n",
    "    threads.append(thread)\n",
    "    thread.start()\n",
    "\n",
    "# Wait for all threads to finish\n",
    "for thread in threads:\n",
    "    thread.join()\n",
    "\n",
    "print(\"Link checking completed.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "806b452d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<Response [429]>\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "query = \"selenium\"\n",
    "headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5)\\\n",
    "            AppleWebKit/537.36 (KHTML, like Gecko) Cafari/537.36'}\n",
    "url = 'https://scholar.google.co.jp/citations?user=AQo7YOEAAAAJ&hl=en'\n",
    "res = requests.get(url, headers=headers)\n",
    "print(res)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "8959e94e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "200\n",
      "Link is okay: https://www.example.com\n",
      "200\n",
      "Link is okay: https://www.google.com\n",
      "200\n",
      "Link is okay: https://www.openai.com\n",
      "429\n",
      "Rate limit exceeded for link: https://scholar.google.co.jp/citations?user=AQo7YOEAAAAJ&hl=en\n",
      "Retrying after 10 seconds...\n",
      "SSL verification error occurred for link: https://sao.fraud.texas.gov/, Error: HTTPSConnectionPool(host='sao.fraud.texas.gov', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))\n",
      "Link is okay (after retry): https://sao.fraud.texas.gov/\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Ricar\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sao.fraud.texas.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "200\n",
      "CAPTCHA challenge encountered for link: https://www.google.com/recaptcha/api2/demo\n",
      "Error occurred for link: https://blocked.example, Error: HTTPSConnectionPool(host='blocked.example', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002798D3DA590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "200\n",
      "Link is okay: https://www.imperva.com/learn/application-security/what-is-captcha/#:~:text=App%20SecurityEssentials-,What%20is%20CAPTCHA,but%20relatively%20easy%20for%20humans\n",
      "Broken link found: https://scholar.google.co.jp/citations?user=AQo7YOEAAAAJ&hl=en\n",
      "Link checking completed.\n"
     ]
    }
   ],
   "source": [
    "import threading\n",
    "import requests\n",
    "import time\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def check_link(link):\n",
    "    try:\n",
    "        headers = {\n",
    "            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'\n",
    "        }\n",
    "        response = requests.get(link, headers=headers)\n",
    "        print(response.status_code)\n",
    "        \n",
    "        # Handle 429 status code\n",
    "        if response.status_code == 429:\n",
    "            print(f\"Rate limit exceeded for link: {link}\")\n",
    "            retry_after = int(response.headers.get('Retry-After', 10))\n",
    "            print(f\"Retrying after {retry_after} seconds...\")\n",
    "            time.sleep(retry_after)\n",
    "            response = requests.get(link, headers=headers)\n",
    "\n",
    "        # Check for CAPTCHA challenge\n",
    "        if \"recaptcha\" in link.lower() and \"demo\" in link.lower():\n",
    "            print(f\"CAPTCHA challenge encountered for link: {link}\")\n",
    "        elif response.status_code == 403:  # Example of a blocked status code\n",
    "            print(f\"Access blocked for link: {link}\")\n",
    "        elif response.status_code != 200:\n",
    "            print(f\"Broken link found: {link}\")\n",
    "        else:\n",
    "            print(f\"Link is okay: {link}\")\n",
    "    except requests.exceptions.SSLError as ssl_error:\n",
    "        # Attempt the request again with verify=False in case of SSL verification error\n",
    "        print(f\"SSL verification error occurred for link: {link}, Error: {ssl_error}\")\n",
    "        try:\n",
    "            response = requests.get(link, headers=headers, verify=False)\n",
    "            if response.status_code != 200:\n",
    "                print(f\"Broken link found (after retry): {link}\")\n",
    "            else:\n",
    "                print(f\"Link is okay (after retry): {link}\")\n",
    "        except requests.exceptions.RequestException as e:\n",
    "            print(f\"Error occurred for link (retry): {link}, Error: {e}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print(f\"Error occurred for link: {link}, Error: {e}\")\n",
    "\n",
    "\n",
    "        \n",
    "        \n",
    "\n",
    "\n",
    "# List of links to check\n",
    "links = [\n",
    "    \"https://www.example.com\",  # Regular page\n",
    "    \"https://www.google.com\",    # Regular page\n",
    "    \"https://www.openai.com\",    # Regular page\n",
    "    \"https://scholar.google.co.jp/citations?user=AQo7YOEAAAAJ&hl=en\",  # Regular page\n",
    "    \"https://sao.fraud.texas.gov/\",  # SSL verification error\n",
    "    \"https://www.google.com/recaptcha/api2/demo\", \n",
    "    \"https://blocked.example\",\n",
    "    \"https://www.imperva.com/learn/application-security/what-is-captcha/#:~:text=App%20SecurityEssentials-,What%20is%20CAPTCHA,but%20relatively%20easy%20for%20humans\",\n",
    "]\n",
    "\n",
    "\n",
    "# Create and start threads for each link\n",
    "threads = []\n",
    "for link in links:\n",
    "    thread = threading.Thread(target=check_link, args=(link,))\n",
    "    threads.append(thread)\n",
    "    thread.start()\n",
    "    time.sleep(1)  # Introduce a delay between requests\n",
    "\n",
    "# Wait for all threads to finish\n",
    "for thread in threads:\n",
    "    thread.join()\n",
    "\n",
    "print(\"Link checking completed.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f51202ad",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a856b6d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "392fa78c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "960828ac",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "feed43c6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e8fc0836",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "27199bcf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD503D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0AE500>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F093FEE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FE5030>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF93D4E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0AC820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E765F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F093F940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F093FAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38F010>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF72B8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0DAF50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E70D62C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0AE500>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFF72500>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFEBC8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED35FBB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFCBCF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0C5720>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED2FF490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA221E40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E70D62C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E7690D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF899210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF7282E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF8993F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0AE620>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF8997E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0AC2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF8997E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0AE500>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF8997E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF7290C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E712BF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8EB7EE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF97D660>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8EB5C30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF7282E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E764FB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFC6DC30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "--- 1 threads: 18.664523601531982 seconds ---\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38F940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E76140>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA1149D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF8990C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD56C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD56C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E77E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0DB6A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E76050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA115510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E76AA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38D210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E7684D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA116170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD4FA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38FC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD4130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA115F30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E75AB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E74250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0DBC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF93DCC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFF72500>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA114340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF89A4A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD1510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38D7B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA116170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0DAC80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.comLink is okay: https://www.example.com\n",
      "\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF8991E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD2620>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD2BF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD2A70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD1120>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD0E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD0BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD0250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD3F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD3F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD0130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "--- 2 threads: 8.977539539337158 seconds ---\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA114610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFEBC730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FE68F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FE43A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FE50C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FE6D40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF8990C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD527D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF89AC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD527D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F093F340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FE4040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0D8100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F093FB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF89A4A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD53310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD53130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F093F7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E775E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E7686DA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E777C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD52CB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF7290C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F093F700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA1168F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0DAC80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA114490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD51DB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFEBD750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E77A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD53550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD528F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38FC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38C070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFDE0A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD53550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38C070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF97EDA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFF718A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD51DB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.openai.com\n",
      "--- 3 threads: 5.662294149398804 seconds ---\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0D9090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF7282E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E774F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA1147F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD50490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD6B30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA115630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD11B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD3340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38FC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA0D8100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E777C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA114340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF899C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA1160B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD525F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD51DB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD5F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD4370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38FC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E76050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287ED38F5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD5BA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD6A40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF72B8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD7DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E76D70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD6B30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287F0FD5630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF72B8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EA1168F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E77220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E76140>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD53130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E75AB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.openai.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EF72B850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E76140>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.example.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD53280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287E8E74520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.example.com\n",
      "Link is okay: https://www.google.com\n",
      "Error occurred for link: https://www.nonexistentlink12345.com, Error: HTTPSConnectionPool(host='www.nonexistentlink12345.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000287EFD53130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Link is okay: https://www.google.com\n",
      "Link is okay: https://www.openai.com\n",
      "Link is okay: https://www.openai.com\n",
      "--- 4 threads: 4.4798853397369385 seconds ---\n",
      "Link checking completed.\n",
      "Time to check 160 links\n",
      "Execution times: {1: 18.664523601531982, 2: 8.977539539337158, 3: 5.662294149398804, 4: 4.4798853397369385}\n"
     ]
    }
   ],
   "source": [
    "import concurrent.futures\n",
    "import requests\n",
    "import time\n",
    "\n",
    "# Function to check a single link\n",
    "def check_link(link):\n",
    "    try:\n",
    "        response = requests.get(link)\n",
    "        if response.status_code != 200:\n",
    "            print(f\"Broken link found: {link}\")\n",
    "        else:\n",
    "            print(f\"Link is okay: {link}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        print(f\"Error occurred for link: {link}, Error: {e}\")\n",
    "\n",
    "# List of links to check\n",
    "links = [\n",
    "    \"https://www.example.com\",\n",
    "    \"https://www.google.com\",\n",
    "    \"https://www.openai.com\",\n",
    "    \"https://www.nonexistentlink12345.com\",\n",
    "]\n",
    "\n",
    "# Dictionary to store execution times\n",
    "execution_times = {}\n",
    "rep=40\n",
    "ammountoflinks=len(links)*rep\n",
    "\n",
    "# Loop over different thread counts\n",
    "for max_threads in range(1,5):\n",
    "    start_time = time.time()\n",
    "\n",
    "    with concurrent.futures.ThreadPoolExecutor(max_threads) as executor:\n",
    "        futures = [executor.submit(check_link, link) for link in links*rep]\n",
    "\n",
    "        # Wait for all tasks to complete\n",
    "        concurrent.futures.wait(futures)\n",
    "\n",
    "    execution_time = time.time() - start_time\n",
    "    execution_times[max_threads] = execution_time\n",
    "\n",
    "    print(f\"--- {max_threads} threads: {execution_time} seconds ---\")\n",
    "\n",
    "print(\"Link checking completed.\")\n",
    "print(f\"Time to check {ammountoflinks} links\")\n",
    "print(\"Execution times:\", execution_times)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ee2b888a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b0191ca",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "37d21881",
   "metadata": {},
   "outputs": [],
   "source": [
    "import openpyxl\n",
    "import requests\n",
    "import threading\n",
    "import tkinter as tk\n",
    "from tkinter.ttk import Progressbar\n",
    "from urllib.parse import urljoin\n",
    "\n",
    "class YourClassNameHere:\n",
    "    def __init__(self):\n",
    "        # Initialize your class here\n",
    "\n",
    "    def check_broken_links(self, excel_file):\n",
    "        try:\n",
    "            print(f\"Opening file: {excel_file}...\")\n",
    "            wb = openpyxl.load_workbook(excel_file)\n",
    "            sheet = wb.active\n",
    "            column_with_links = 'A'\n",
    "            column_with_templates = 'B'\n",
    "\n",
    "            broken_links_report = []\n",
    "            total_links_checked = 0\n",
    "            total_links = 0\n",
    "\n",
    "            for cell in sheet[column_with_links]:\n",
    "                if cell.value:\n",
    "                    total_links += 1\n",
    "\n",
    "            print(f\"Checking {total_links} links inside {excel_file}...\")\n",
    "            self.total_pages = len([cell for cell in sheet[column_with_links] if cell.value])\n",
    "\n",
    "            # Create a Progressbar widget for the overall progress\n",
    "            progress_bar = Progressbar(self.root, orient='horizontal', length=300, maximum=self.total_pages, mode='determinate')\n",
    "            progress_bar.pack()\n",
    "\n",
    "            threads = []\n",
    "\n",
    "            for link_cell, template_cell in zip(sheet[column_with_links], sheet[column_with_templates]):\n",
    "                if link_cell.value:\n",
    "                    link = link_cell.value\n",
    "                    template = template_cell.value\n",
    "\n",
    "                    total_links_checked += 1\n",
    "                    page_links = self.controller.get_links_from_page(link)\n",
    "\n",
    "                    # Create a thread pool for checking links\n",
    "                    thread_pool = []\n",
    "\n",
    "                    for i, page_link in enumerate(page_links):\n",
    "                        thread = threading.Thread(target=self.check_link, args=(link, page_link, template, broken_links_report))\n",
    "                        thread.start()\n",
    "                        thread_pool.append(thread)\n",
    "\n",
    "                        if len(thread_pool) >= 34:\n",
    "                            for thread in thread_pool:\n",
    "                                thread.join()\n",
    "                            thread_pool = []\n",
    "\n",
    "                    threads.extend(thread_pool)\n",
    "\n",
    "                    # Update page progress label\n",
    "                    self.update_page_progress(total_links_checked, self.total_pages)\n",
    "\n",
    "                    self.current_page += 1\n",
    "\n",
    "                progress_bar['value'] = total_links_checked\n",
    "                self.root.update_idletasks()\n",
    "\n",
    "            # Wait for all threads to finish\n",
    "            for thread in threads:\n",
    "                thread.join()\n",
    "\n",
    "            print(\"\\nLink checking completed.\")\n",
    "            print(f\"Total pages checked: {total_links_checked}\")\n",
    "            print(f\"Total broken links found: {len(broken_links_report)}\")\n",
    "            progress_bar.destroy()\n",
    "            return broken_links_report\n",
    "        except openpyxl.utils.exceptions.InvalidFileException:\n",
    "            print(f\"Error: Unable to open the file '{excel_file}'. Please check if it's a valid Excel file.\")\n",
    "            return []\n",
    "        except Exception as e:\n",
    "            print(f\"Error: An unexpected error occurred while processing the file '{excel_file}': {e}\")\n",
    "            return []\n",
    "\n",
    "    def check_link(self, link, page_link, template, broken_links_report):\n",
    "        # Your existing link checking code here\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "08ad69dc",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "358436a0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b58bc3bb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5e3d689",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "d60e6eac",
   "metadata": {},
   "outputs": [],
   "source": [
    "scripts='''\n",
    "https://www.utep.edu/marketing-and-communications/faculty-photograph-library/index.html\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "https://www.utep.edu/engineering/tcm/tcm.html\n",
    "https://utepathletics.com/sports/2017/6/7/trads-history-traditions-html.aspx\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "https://utepminers.com/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/home\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/home\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "http://masterplan.utep.edu/\n",
    "https://www.utep.edu/about/about-utep.html\n",
    "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
    "https://www.utep.edu/student-affairs/admissions/how-to-apply/freshman.html\n",
    "https://www.utep.edu/student-affairs/admissions/how-to-apply/international.html\n",
    "https://www.utep.edu/student-affairs/admissions/how-to-apply/transfer.html\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "https://utepminers.com/\n",
    "http://studentlife.utep.edu/\n",
    "http://alumni.utep.edu/\n",
    "http://alumni.utep.edu/page.aspx?pid=1255\n",
    "https://www.utep.edu/about/divisions/asset-management-and-development.html\n",
    "https://www.utep.edu/about/divisions/external-relations.html\n",
    "https://www.utep.edu/about/divisions/administration-and-oversight.html\n",
    "https://www.utep.edu/about/divisions/March-2018/Information%20Resources%20and%20Planning-rev3-9-18.pdf\n",
    "https://www.utep.edu/about/divisions/organized-res-units.html\n",
    "https://www.utep.edu/about/about-utep.html\n",
    "http://masterplan.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/home\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://www.utepathletics.com/\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/home\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://givingto.utep.edu/home\n",
    "https://utepminers.com/\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://alumni.utep.edu/\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://utepminers.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://alumni.utep.edu/\n",
    "https://utepminers.com/\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/CentennialLectureSeries.html\n",
    "https://www.utep.edu/about/presidents-speeches.html\n",
    "https://www.utep.edu/about/committee-on-diversity.html\n",
    "https://www.utep.edu/about/millennium-lecture-series.html\n",
    "http://sao.fraud.state.tx.us/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
    "https://utepminers.com/\n",
    "http://www.utepathletics.com/\n",
    "http://givingto.utep.edu/home\n",
    "http://givingto.utep.edu/page.aspx?pid=1425\n",
    "http://givingto.utep.edu/ways-of-giving\n",
    "http://alumni.utep.edu/\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/presidents-speeches.html\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/CentennialLectureSeries.html\n",
    "https://www.utep.edu/about/millennium-lecture-series.html\n",
    "https://www.utep.edu/about/committee-on-diversity.html\n",
    "http://sao.fraud.state.tx.us/\n",
    "\n",
    "'''\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "ce30ee4d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://www.utep.edu/marketing-and-communications/faculty-photograph-library/index.html\n",
      "https://utepminers.com/\n",
      "http://givingto.utep.edu/page.aspx?pid=1425\n",
      "http://givingto.utep.edu/home\n",
      "http://givingto.utep.edu/ways-of-giving\n",
      "http://alumni.utep.edu/\n",
      "http://sao.fraud.state.tx.us/\n",
      "https://www.utep.edu/engineering/tcm/tcm.html\n",
      "https://utepathletics.com/sports/2017/6/7/trads-history-traditions-html.aspx\n",
      "http://masterplan.utep.edu/\n",
      "https://www.utep.edu/about/about-utep.html\n",
      "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
      "https://www.utep.edu/student-affairs/admissions/how-to-apply/freshman.html\n",
      "https://www.utep.edu/student-affairs/admissions/how-to-apply/international.html\n",
      "https://www.utep.edu/student-affairs/admissions/how-to-apply/transfer.html\n",
      "http://studentlife.utep.edu/\n",
      "http://alumni.utep.edu/page.aspx?pid=1255\n",
      "https://www.utep.edu/about/divisions/asset-management-and-development.html\n",
      "https://www.utep.edu/about/divisions/external-relations.html\n",
      "https://www.utep.edu/about/divisions/administration-and-oversight.html\n",
      "https://www.utep.edu/about/divisions/March-2018/Information%20Resources%20and%20Planning-rev3-9-18.pdf\n",
      "https://www.utep.edu/about/divisions/organized-res-units.html\n",
      "http://www.utepathletics.com/\n",
      "https://www.utep.edu/majors-and-degrees/\n",
      "https://www.utep.edu/about/presidents-speeches-in/\n",
      "https://www.utep.edu/about/CentennialLectureSeries.html\n",
      "https://www.utep.edu/about/presidents-speeches.html\n",
      "https://www.utep.edu/about/committee-on-diversity.html\n",
      "https://www.utep.edu/about/millennium-lecture-series.html\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "# Split the input string into a list of links using regex\n",
    "links = re.findall(r'https?://[^\\s/$.?#].[^\\s]*', scripts)\n",
    "\n",
    "# Remove duplicates while preserving the order\n",
    "unique_links = list(dict.fromkeys(links))\n",
    "\n",
    "# Print the list of unique links\n",
    "for link in unique_links:\n",
    "    print(link)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "1620a4ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "scripts2='''\n",
    "https://www.utep.edu/marketing-and-communications/faculty-photograph-library/index.html\n",
    "https://www.utep.edu/engineering/tcm/tcm.html\n",
    "https://www.utep.edu/student-affairs/admissions/how-to-apply/transfer.html\n",
    "https://www.utep.edu/about/about-utep.html\n",
    "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
    "https://www.utep.edu/student-affairs/admissions/how-to-apply/international.html\n",
    "https://www.utep.edu/student-affairs/admissions/how-to-apply/freshman.html\n",
    "https://www.utep.edu/about/divisions/asset-management-and-development.html\n",
    "https://www.utep.edu/about/about-utep.html\n",
    "https://www.utep.edu/about/divisions/external-relations.html\n",
    "https://www.utep.edu/about/divisions/organized-res-units.html\n",
    "https://www.utep.edu/about/divisions/March-2018/Information%20Resources%20and%20Planning-rev3-9-18.pdf\n",
    "https://www.utep.edu/about/divisions/administration-and-oversight.html\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/millennium-lecture-series.html\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/about/CentennialLectureSeries.html\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/about/presidents-speeches.html\n",
    "https://www.utep.edu/about/committee-on-diversity.html\n",
    "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
    "https://www.utep.edu/majors-and-degrees/\n",
    "https://www.utep.edu/about/presidents-speeches.html\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/CentennialLectureSeries.html\n",
    "https://www.utep.edu/about/presidents-speeches-in/\n",
    "https://www.utep.edu/about/committee-on-diversity.html\n",
    "https://www.utep.edu/about/millennium-lecture-series.html\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bd57e597",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "782f9287",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://www.utep.edu/marketing-and-communications/faculty-photograph-library/index.html\n",
      "https://www.utep.edu/engineering/tcm/tcm.html\n",
      "https://www.utep.edu/student-affairs/admissions/how-to-apply/transfer.html\n",
      "https://www.utep.edu/about/about-utep.html\n",
      "https://www.utep.edu/university-communications/faculty-photograph-library/index.html\n",
      "https://www.utep.edu/student-affairs/admissions/how-to-apply/international.html\n",
      "https://www.utep.edu/student-affairs/admissions/how-to-apply/freshman.html\n",
      "https://www.utep.edu/about/divisions/asset-management-and-development.html\n",
      "https://www.utep.edu/about/divisions/external-relations.html\n",
      "https://www.utep.edu/about/divisions/organized-res-units.html\n",
      "https://www.utep.edu/about/divisions/March-2018/Information%20Resources%20and%20Planning-rev3-9-18.pdf\n",
      "https://www.utep.edu/about/divisions/administration-and-oversight.html\n",
      "https://www.utep.edu/majors-and-degrees/\n",
      "https://www.utep.edu/about/presidents-speeches-in/\n",
      "https://www.utep.edu/about/millennium-lecture-series.html\n",
      "https://www.utep.edu/about/CentennialLectureSeries.html\n",
      "https://www.utep.edu/about/presidents-speeches.html\n",
      "https://www.utep.edu/about/committee-on-diversity.html\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "# Split the input string into a list of links using regex\n",
    "links2 = re.findall(r'https?://[^\\s/$.?#].[^\\s]*', scripts2)\n",
    "\n",
    "# Remove duplicates while preserving the order\n",
    "unique_links2 = list(dict.fromkeys(links2))\n",
    "\n",
    "# Print the list of unique links\n",
    "for link in unique_links2:\n",
    "    print(link)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "0f93072d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n"
     ]
    }
   ],
   "source": [
    "print(unique_links2 not in unique_links)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "23c98dc0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://utepminers.com/\n",
      "http://givingto.utep.edu/page.aspx?pid=1425\n",
      "http://givingto.utep.edu/home\n",
      "http://givingto.utep.edu/ways-of-giving\n",
      "http://alumni.utep.edu/\n",
      "http://sao.fraud.state.tx.us/\n",
      "https://utepathletics.com/sports/2017/6/7/trads-history-traditions-html.aspx\n",
      "http://masterplan.utep.edu/\n",
      "http://studentlife.utep.edu/\n",
      "http://alumni.utep.edu/page.aspx?pid=1255\n",
      "http://www.utepathletics.com/\n"
     ]
    }
   ],
   "source": [
    "# Find links in the first list that are not in the second list\n",
    "links_not_in_list2 = [link for link in unique_links if link not in unique_links2]\n",
    "\n",
    "# Print the links that are not in the second list\n",
    "for link in links_not_in_list2:\n",
    "    print(link)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "90f99456",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
